import { ValueObject } from '../../shared/domain/value-object';
import { ValidationError } from '../../shared/errors/index';
import { MESSAGE_CODES } from '../../shared/constants/message-codes';

/**
 * UserId Value Object
 * - DB는 SERIAL (INTEGER) 사용
 */
export class UserId extends ValueObject<number> {
  private constructor(value: number) {
    super(value);
  }

  static create(id: number): UserId {
    if (!Number.isInteger(id) || id <= 0) {
      throw new ValidationError('Invalid user ID', undefined, MESSAGE_CODES.USER.INVALID_USER_ID);
    }
    return new UserId(id);
  }

  static generate(): UserId {
    // 새 ID는 데이터베이스에서 SERIAL로 자동 생성되므로
    // 이 메서드는 사용하지 않거나 에러를 던집니다
    throw new ValidationError('UserId is auto-generated by database', undefined, MESSAGE_CODES.SYSTEM.CANNOT_PROCESS_REQUEST);
  }

  toString(): string {
    return this.value.toString();
  }
}
