/**
 * 메시지 코드 상수 정의
 * 데이터베이스의 message_codes 테이블과 동기화되어야 함
 */

export const MESSAGE_CODES = {
  // 인증 관련 메시지
  AUTH: {
    INVALID_CREDENTIALS: 'AUTH_001',
    NO_TOKEN: 'AUTH_002',
    INVALID_TOKEN: 'AUTH_003',
    TOKEN_EXPIRED: 'AUTH_004',
    ACCESS_DENIED: 'AUTH_005',
    LOGIN_SUCCESS: 'AUTH_006',
    LOGOUT_SUCCESS: 'AUTH_007',
    EMAIL_EXISTS: 'AUTH_008',
    REGISTER_SUCCESS: 'AUTH_009',
    PASSWORD_MISMATCH: 'AUTH_010',
    EMAIL_VERIFICATION_REQUIRED: 'AUTH_011',
    EMAIL_VERIFIED: 'AUTH_012',
    INVALID_VERIFICATION_CODE: 'AUTH_013',
    VERIFICATION_EMAIL_SENT: 'AUTH_014',
    INVALID_REFRESH_TOKEN: 'AUTH_015',
    TOKEN_REFRESHED: 'AUTH_016',
  },

  // 사용자 관련 메시지
  USER: {
    NOT_FOUND: 'USER_001',
    PROFILE_UPDATED: 'USER_002',
    INVALID_USER_ID: 'USER_003',
    PROFILE_IMAGE_UPLOAD_FAILED: 'USER_004',
    PASSWORD_CHANGED: 'USER_005',
    INCORRECT_CURRENT_PASSWORD: 'USER_006',
    NICKNAME_IN_USE: 'USER_007',
    USER_DELETED: 'USER_008',
  },

  // 아티클 관련 메시지
  ARTICLE: {
    NOT_FOUND: 'ARTICLE_001',
    CREATED: 'ARTICLE_002',
    UPDATED: 'ARTICLE_003',
    DELETED: 'ARTICLE_004',
    NO_CREATE_PERMISSION: 'ARTICLE_005',
    NO_EDIT_PERMISSION: 'ARTICLE_006',
    NO_DELETE_PERMISSION: 'ARTICLE_007',
    TITLE_REQUIRED: 'ARTICLE_008',
    CONTENT_REQUIRED: 'ARTICLE_009',
    PUBLISHED: 'ARTICLE_010',
    SAVED_AS_DRAFT: 'ARTICLE_011',
    ALREADY_PUBLISHED: 'ARTICLE_012',
    LIKED: 'ARTICLE_013',
    UNLIKED: 'ARTICLE_014',
    ALREADY_LIKED: 'ARTICLE_015',
  },

  // 카테고리 관련 메시지
  CATEGORY: {
    NOT_FOUND: 'CATEGORY_001',
    ALREADY_EXISTS: 'CATEGORY_002',
    CREATED: 'CATEGORY_003',
    UPDATED: 'CATEGORY_004',
    CANNOT_DELETE_WITH_ARTICLES: 'CATEGORY_005',
  },

  // 태그 관련 메시지
  TAG: {
    NOT_FOUND: 'TAG_001',
    ADDED: 'TAG_002',
    REMOVED: 'TAG_003',
    ALREADY_EXISTS: 'TAG_004',
  },

  // 팔로우 관련 메시지
  FOLLOW: {
    FOLLOWED: 'FOLLOW_001',
    UNFOLLOWED: 'FOLLOW_002',
    ALREADY_FOLLOWING: 'FOLLOW_003',
    CANNOT_FOLLOW_SELF: 'FOLLOW_004',
    NOT_FOLLOWING: 'FOLLOW_005',
  },

  // 댓글 관련 메시지
  COMMENT: {
    CREATED: 'COMMENT_001',
    UPDATED: 'COMMENT_002',
    DELETED: 'COMMENT_003',
    NOT_FOUND: 'COMMENT_004',
    NO_EDIT_PERMISSION: 'COMMENT_005',
    NO_DELETE_PERMISSION: 'COMMENT_006',
    CONTENT_REQUIRED: 'COMMENT_007',
  },

  // 시스템 관련 메시지
  SYSTEM: {
    INTERNAL_ERROR: 'SYSTEM_001',
    CANNOT_PROCESS_REQUEST: 'SYSTEM_002',
    BAD_REQUEST: 'SYSTEM_003',
    RESOURCE_NOT_FOUND: 'SYSTEM_004',
    SERVICE_UNAVAILABLE: 'SYSTEM_005',
    REQUEST_TIMEOUT: 'SYSTEM_006',
    MAINTENANCE_SCHEDULED: 'SYSTEM_007',
    NEW_VERSION_AVAILABLE: 'SYSTEM_008',
  },

  // 유효성 검사 관련 메시지
  VALIDATION: {
    REQUIRED_FIELD_MISSING: 'VALIDATION_001',
    INVALID_EMAIL_FORMAT: 'VALIDATION_002',
    PASSWORD_TOO_SHORT: 'VALIDATION_003',
    PASSWORD_COMPLEXITY: 'VALIDATION_004',
    FILE_TOO_LARGE: 'VALIDATION_005',
    UNSUPPORTED_FILE_FORMAT: 'VALIDATION_006',
    NICKNAME_LENGTH: 'VALIDATION_007',
    TITLE_TOO_LONG: 'VALIDATION_008',
  },

  // 보안 관련 메시지
  SECURITY: {
    SUSPICIOUS_ACTIVITY: 'SECURITY_001',
    TOO_MANY_ATTEMPTS: 'SECURITY_002',
    IP_BLOCKED: 'SECURITY_003',
    ACCOUNT_LOCKED: 'SECURITY_004',
    NEW_DEVICE_LOGIN: 'SECURITY_005',
  },

  // 온보딩 관련 메시지
  ONBOARDING: {
    INTERESTS_SAVED: 'ONBOARDING_001',
    MINIMUM_INTERESTS_REQUIRED: 'ONBOARDING_002',
    COMPLETED: 'ONBOARDING_003',
    COMPLETE_FOR_RECOMMENDATIONS: 'ONBOARDING_004',
  },

  // 추천 관련 메시지
  RECOMMENDATION: {
    LOADED: 'RECOMMENDATION_001',
    NO_RECOMMENDATIONS: 'RECOMMENDATION_002',
    SYSTEM_ERROR: 'RECOMMENDATION_003',
  },

  // 작가 관련 메시지
  WRITER: {
    REGISTERED: 'WRITER_001',
    PROFILE_NOT_FOUND: 'WRITER_002',
    PROFILE_UPDATED: 'WRITER_003',
    NO_REGISTRATION_PERMISSION: 'WRITER_004',
    BIO_REQUIRED: 'WRITER_005',
  },

  // 관리자 관련 메시지
  ADMIN: {
    PERMISSION_REQUIRED: 'ADMIN_001',
    OPERATION_COMPLETED: 'ADMIN_002',
    ACTIVITY_LOGGED: 'ADMIN_003',
    INVALID_TOKEN: 'ADMIN_004',
  },

  // 이메일 관련 메시지
  EMAIL: {
    SENT: 'EMAIL_001',
    SEND_FAILED: 'EMAIL_002',
    QUEUED: 'EMAIL_003',
    VERIFY_ADDRESS: 'EMAIL_004',
  },
} as const;

// 타입 정의
export type MessageCode = typeof MESSAGE_CODES[keyof typeof MESSAGE_CODES][keyof typeof MESSAGE_CODES[keyof typeof MESSAGE_CODES]];

// 메시지 타입 정의
export enum MessageType {
  SYSTEM = 'SYSTEM',
  ERROR = 'ERROR',
  WARNING = 'WARNING',
  INFO = 'INFO',
  SUCCESS = 'SUCCESS',
  VALIDATION = 'VALIDATION',
  SECURITY = 'SECURITY',
}

// 메시지 카테고리 정의
export enum MessageCategory {
  AUTH = 'AUTH',
  USER = 'USER',
  ARTICLE = 'ARTICLE',
  CATEGORY = 'CATEGORY',
  TAG = 'TAG',
  FOLLOW = 'FOLLOW',
  COMMENT = 'COMMENT',
  SYSTEM = 'SYSTEM',
  VALIDATION = 'VALIDATION',
  SECURITY = 'SECURITY',
  ONBOARDING = 'ONBOARDING',
  RECOMMENDATION = 'RECOMMENDATION',
  WRITER = 'WRITER',
  ADMIN = 'ADMIN',
  EMAIL = 'EMAIL',
}

// 메시지 코드 정보 인터페이스
export interface MessageCodeInfo {
  code: string;
  type: MessageType;
  category: MessageCategory;
  messageKo: string;
  messageEn: string;
  httpStatusCode?: number;
}